// Generated by CoffeeScript 1.3.1
(function() {
  var Less, css, fs;

  fs = require('fs');

  Less = require('less');

  css = (function() {

    css.name = 'css';

    function css() {}

    css.compile = function(callback, mimified) {
      var parser, path,
        _this = this;
      if (mimified == null) {
        mimified = false;
      }
      try {
        path = "./css/index.less";
        parser = new Less.Parser({
          paths: ['./css/bootstrap', './css/'],
          filename: 'index.less'
        });
        return fs.readFile(path, "utf8", function(err, data) {
          if (err) {
            console.error(err);
            callback("", false);
          }
          return parser.parse(data, function(err, css) {
            var content;
            if (err) {
              console.error(err);
              return callback("", false);
            } else {
              content = css.toCSS();
              if (mimified) {
                content = content.replace(/(\s)+/g, "$1");
              }
              return callback(content, true);
            }
          });
        });
      } catch (err) {
        return callback("", false);
      }
    };

    return css;

  })();

  module.exports = css;

}).call(this);
