// Generated by CoffeeScript 1.3.1
(function() {
  var Opfserver, css, jscompiler;

  css = require('./css');

  jscompiler = require('./jscompiler');

  Opfserver = (function() {

    Opfserver.name = 'Opfserver';

    function Opfserver() {}

    Opfserver.setupRoutes = function(app) {
      var Less,
        _this = this;
      Less = require('less');
      app.get('/application.js', jscompiler.compile().createServer());
      return app.get('/application.css', function(req, res) {
        var content;
        return content = css.compile(function(content, success) {
          if (success) {
            res.header("Content-type", "text/css");
            return res.send(content);
          } else {
            return res.send(500);
          }
        });
      });
    };

    return Opfserver;

  })();

  module.exports = Opfserver;

}).call(this);
